[[LibXSPEC_Relxill]]
arch = "aarch64"
git-tree-sha1 = "ee518914930458f86ede1e099f8aec3ecf066410"
libgfortran_version = "5.0.0"
os = "macos"

    [[LibXSPEC_Relxill.download]]
    sha256 = "d3ff3e0d3a52de1370d7c682fcb17025d3c4e351f0c5ac23ba78316fa8ed427f"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
git-tree-sha1 = "2c82020e3464c75a773ce628973cf958f4a9c3a5"
libgfortran_version = "4.0.0"
os = "macos"

    [[LibXSPEC_Relxill.download]]
    sha256 = "9a69046e3eeb61a4a17a13c941010cc600fd928b444360a81305a277366abda7"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
git-tree-sha1 = "2c82020e3464c75a773ce628973cf958f4a9c3a5"
libgfortran_version = "5.0.0"
os = "macos"

    [[LibXSPEC_Relxill.download]]
    sha256 = "9a69046e3eeb61a4a17a13c941010cc600fd928b444360a81305a277366abda7"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24c5cb13291f194ee582ae309bee2c31ae0b0298"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LibXSPEC_Relxill.download]]
    sha256 = "d6e3bfc33dda7812bd621f10f3a1ff70d5f0ff9f8d946f40497ed1c915b2d7c4"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f5041daaa82e1cab62166c1d2475eb15aac748a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LibXSPEC_Relxill.download]]
    sha256 = "34c2cf28ccc77722ce21150077ebe95a3d4577fb2b412cc8b7be80ecc44e338c"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acb9c5151b67936d1899da9ffb11cc13db5ed178"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LibXSPEC_Relxill.download]]
    sha256 = "71407d3855f83e5f6f9d96034707b7391e29e2f3a941a5eae4c8ed70742a42ff"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[LibXSPEC_Relxill]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96745ba9dab0789623716be017bc40a91b87958b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LibXSPEC_Relxill.download]]
    sha256 = "8cb415142ce9e974c395b086dbc028b683cf6cffbad3482180e517243a013c17"
    url = "https://github.com/astro-group-bristol/LibXSPEC_Relxill_jll.jl/releases/download/LibXSPEC_Relxill-v0.2.4+0/LibXSPEC_Relxill.v0.2.4.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
