# Autogenerated wrapper script for LibXSPEC_Relxill_jll for aarch64-apple-darwin-libgfortran5
export libXSPEC_relxill

using CompilerSupportLibraries_jll
using LibXSPEC_jll
JLLWrappers.@generate_wrapper_header("LibXSPEC_Relxill")
JLLWrappers.@declare_library_product(libXSPEC_relxill, "@rpath/relxill")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, LibXSPEC_jll)
    JLLWrappers.@init_library_product(
        libXSPEC_relxill,
        "lib/relxill.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
    # set environment variable needed by the models
    ENV["RELXILL_TABLE_PATH"] = LibXSPEC_Relxill_jll.artifact_dir * "/data"

end  # __init__()
